### ISSUE TITLE
Anndemand and ddays for mvd

### ISSUE THREAD

**Issue by leopoldoagorio** [leopoldoagorio/UTER#2]
We got the economic data, and could make the mvd.econ time series:
![image (2)](https://user-images.githubusercontent.com/39858159/227257123-2c3bdeb3-cb92-4d66-bd7b-bc43fc8496c3.png)

However, anndemand and ddays in the australian version were computed only for summer. Uruguayan summer has not had a temperature dependant behaviour in the earliest years of our dataset 2008-2013 as shown in the following graph:
![image (1)](https://user-images.githubusercontent.com/39858159/227257464-fb1b365b-3474-4aea-873e-bca010e6b5fa.png)

We have to decide how to proceed. My personal opinion is we use Uruguayan winter data and try to run the model only with Uruguay winter years.

RFC Request For Comment @frumgar @JPCarballal

**Comment by frumgar** [comment]
Por lo que entiendo, estás proponiendo tener dos hilos: uno para el verano y otro para el invierno. puede ser. 
no me queda del todo dónde está la dificultad de extender lo de australia a todo el año. asumo que está en el código.

**Comment by leopoldoagorio** [comment]
ver #3

**Comment by JPCarballal** [comment]
Cerrado con lo discutido en #3
