### ISSUE TITLE
Hacer primer corrida mvd MEFM

### ISSUE THREAD

**Issue by leopoldoagorio** [leopoldoagorio/UTER#6]
- [ ] Pelearse con el error de factors

**Comment by JPCarballal** [comment]
Error in `contrasts<-`(`*tmp*`, value = contr.funs[1 + isOF[nn]]) : 
  contrasts can be applied only to factors with 2 or more levels

**Comment by JPCarballal** [comment]
Empezamos a trabajar en esto en el archivo mvd_MEFM y tuvimos ese error
